# FrozenLake Environment

- S denotes the starting state
- F denotes the frozen state
- H denotes the hole state
- G denotes the goal state

**Objective:** Get to the goal state from S without visiting the H state.
**Reward Attribution:** +1 for G, 0 otherwise

In [23]:
#Creating and Rendering the environment
import gymnasium as gym

env = gym.make("FrozenLake-v1", render_mode="ansi")
env.reset()
print(env.render())


SFFF
FHFH
FFFH
HFFG



In [24]:
#State space
print(env.observation_space)

Discrete(16)


In [25]:
#Action space
print(env.action_space)

Discrete(4)


Action Encoding

1. 0 -> left
2. 1 -> down
3. 2 -> right
4. 3 -> up

In [26]:
#env.P[state][action]
#Move right from state 0(S)
print(env.unwrapped.P[0][2])
#Move down from state 3(F)
print(env.unwrapped.P[3][1])

[(0.33333333333333337, 4, 0, False), (0.3333333333333333, 1, 0, False), (0.33333333333333337, 0, 0, False)]
[(0.33333333333333337, 2, 0, False), (0.3333333333333333, 7, 0, True), (0.33333333333333337, 3, 0, False)]


In [27]:
print(env.render())


SFFF
FHFH
FFFH
HFFG



In [28]:
print(env.step(1))
print(env.render())

(0, 0, False, False, {'prob': 0.33333333333333337})
  (Down)
SFFF
FHFH
FFFH
HFFG



## An Episode

In [33]:
# Episode

import gymnasium as gym

env = gym.make("FrozenLake-v1", render_mode="ansi")
state = env.reset()

print('Time Step 0 :')
print(env.render())

num_timesteps = 20

for t in range(num_timesteps):
    random_action = env.action_space.sample()
    observation, reward, done, truncated,info = env.step(random_action)
    # If we reach terminal state
    print (f'Time Step {t+1}')
    print(env.render())
    if done:
        print(f'Reached Terminal State {observation} at time step {t + 1}')
        break

Time Step 0 :

SFFF
FHFH
FFFH
HFFG

Time Step 1
  (Left)
SFFF
FHFH
FFFH
HFFG

Time Step 2
  (Up)
SFFF
FHFH
FFFH
HFFG

Time Step 3
  (Up)
SFFF
FHFH
FFFH
HFFG

Time Step 4
  (Down)
SFFF
FHFH
FFFH
HFFG

Reached Terminal State 5 at time step 4


## Series of Episodes

In [1]:
import gymnasium as gym

env = gym.make("FrozenLake-v1", render_mode="human")

num_episodes = 10
num_timesteps = 20

for i in range(num_episodes):
    state, info = env.reset()
    print(f'Episode {i}, Time Step 0:')
    env.render()

    for t in range(num_timesteps):
        random_action = env.action_space.sample()
        observation, reward, done, truncated, info = env.step(random_action)
        print(f'Time Step {t + 1}')
        env.render()

        if done or truncated:
            print(f'Reached Terminal State {observation} at time step {t + 1}')
            break

env.close()

Episode 0, Time Step 0:
Time Step 1
Time Step 2
Reached Terminal State 5 at time step 2
Episode 1, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Reached Terminal State 12 at time step 3
Episode 2, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Time Step 10
Time Step 11
Time Step 12
Time Step 13
Time Step 14
Time Step 15
Time Step 16
Time Step 17
Time Step 18
Time Step 19
Time Step 20
Episode 3, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Reached Terminal State 7 at time step 8
Episode 4, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Reached Terminal State 12 at time step 4
Episode 5, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Reached Terminal State 5 at time step 3
Episode 6, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Reached Terminal State 12 at time step 3
Episode 7, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Ti

## The Cart-Pole Environment

- State space comprises continuous values
- space values here include cart position, cart velocity, pole angle, pole velocity at the tip
- cart position ranges from -4.8 to 4.8
- the cart velocity ranges from -$\infty$ to +$\infty$ 
- the value of the pole angle ranges from -0.418 radians to 0.418
- the value of the pole velocity at the tip ranges from -$\infty$ to +$\infty$ 
- the state space is an array of values of the form **[cart_position, cart_velocity, pole angle, pole velocity at tip]**
- the action space is discrete.
- 0 -> push cart to the left
- 1 -> push cart to the right
- Agent receives a reward of +1 every time the pole stands up on the cart.


In [10]:
import gymnasium as gym

env = gym.make("CartPole-v1", render_mode="human")
state, info = env.reset()
print(state)
env.render()
env.close()

[-0.02970638  0.03572089  0.04478719  0.02578104]


In [11]:
#State space information
print(env.observation_space),
print(env.observation_space.high)
print(env.observation_space.low)

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)
[4.8               inf 0.41887903        inf]
[-4.8               -inf -0.41887903        -inf]


In [12]:
#Action space
print(env.action_space)

Discrete(2)


In [15]:
import gymnasium as gym

env = gym.make("CartPole-v1", render_mode="human")

num_episodes = 100
num_timesteps = 50

for i in range(num_episodes):
    Return = 0
    state, info = env.reset()
    print(f'Episode {i}, Time Step 0:')
    env.render()

    for t in range(num_timesteps):
        random_action = env.action_space.sample()
        observation, reward, done, truncated, info = env.step(random_action)
        Return = Return + reward
        print(f'Time Step {t + 1}')
        env.render()

        if done or truncated:
            print(f'Reached Terminal State {observation} at time step {t + 1}')
            break

    if i % 10 == 0:
        print(f'Episode: {i}, Return: {Return}')

env.close()

Episode 0, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Time Step 10
Time Step 11
Time Step 12
Time Step 13
Time Step 14
Time Step 15
Time Step 16
Time Step 17
Time Step 18
Time Step 19
Time Step 20
Time Step 21
Reached Terminal State [-0.13378033 -0.63374937  0.2218585   1.4366533 ] at time step 21
Episode: 0, Return: 21.0
Episode 1, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Reached Terminal State [ 0.13437319  0.6460166  -0.2139422  -1.1506716 ] at time step 9
Episode 2, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Time Step 10
Time Step 11
Reached Terminal State [-0.10389672 -1.0072577   0.2135622   1.801366  ] at time step 11
Episode 3, Time Step 0:
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9

## Value Iteration

In [16]:
import numpy as np


def optimum_value(env, num_iterations=1000, threshold=1e-20, gamma=1.0):
    # Initialize value table
    value_table = np.zeros(env.observation_space.n)

    for i in range(num_iterations):
        # On every iteration, use the updated value table
        updated_value_table = np.copy(value_table)

        for s in range(env.observation_space.n):
            Q_values = [
                sum([prob * (r + gamma * updated_value_table[s_])
                     for prob, s_, r, _ in env.unwrapped.P[s][a]])
                for a in range(env.action_space.n)
            ]
            value_table[s] = max(Q_values)

        if np.sum(np.fabs(updated_value_table - value_table)) <= threshold:
            break

    return value_table


def extract_policy(value_table, env, gamma=1.0):
    policy = np.zeros(env.observation_space.n)

    for s in range(env.observation_space.n):
        Q_values = [
            sum([prob * (r + gamma * value_table[s_])
                 for prob, s_, r, _ in env.unwrapped.P[s][a]])
            for a in range(env.action_space.n)
        ]
        policy[s] = np.argmax(np.array(Q_values))

    return policy


def value_iteration(env, num_iterations=1000, threshold=1e-20, gamma=1.0):
    optimum_value_function = optimum_value(env, num_iterations, threshold, gamma)
    optimal_policy = extract_policy(optimum_value_function, env, gamma)
    print(optimal_policy)
    return optimal_policy

In [ ]:
import gymnasium as gym

env = gym.make("FrozenLake-v1", render_mode="human")
value_iteration(env, num_iterations=1000, threshold=1e-20, gamma=1.0)

[0. 3. 3. 3. 0. 0. 0. 0. 3. 1. 0. 0. 0. 2. 1. 0.]


array([0., 3., 3., 3., 0., 0., 0., 0., 3., 1., 0., 0., 0., 2., 1., 0.])

In [19]:
import gymnasium as gym
import time

env = gym.make("FrozenLake-v1", render_mode="human")

policy = value_iteration(env, num_iterations=1000, threshold=1e-20, gamma=1.0)

state, info = env.reset()
env.render()

num_timesteps = 100  # safety cap in case the agent never reaches a terminal state

for t in range(num_timesteps):
    action = int(policy[state])
    state, reward, done, truncated, info = env.step(action)
    print(f'Time Step {t + 1}')
    env.render()

    if done or truncated:
        print(f'Reached Terminal State {state} at time step {t + 1}')
        time.sleep(5)  
        break

env.close()

[0. 3. 3. 3. 0. 0. 0. 0. 3. 1. 0. 0. 0. 2. 1. 0.]
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Time Step 10
Time Step 11
Time Step 12
Time Step 13
Time Step 14
Time Step 15
Time Step 16
Time Step 17
Time Step 18
Time Step 19
Time Step 20
Time Step 21
Time Step 22
Time Step 23
Time Step 24
Time Step 25
Time Step 26
Time Step 27
Time Step 28
Time Step 29
Time Step 30
Time Step 31
Time Step 32
Time Step 33
Time Step 34
Time Step 35
Time Step 36
Time Step 37
Time Step 38
Time Step 39
Time Step 40
Time Step 41
Time Step 42
Time Step 43
Time Step 44
Time Step 45
Time Step 46
Time Step 47
Time Step 48
Time Step 49
Time Step 50
Time Step 51
Time Step 52
Time Step 53
Time Step 54
Time Step 55
Time Step 56
Time Step 57
Time Step 58
Time Step 59
Time Step 60
Time Step 61
Time Step 62
Time Step 63
Time Step 64
Time Step 65
Time Step 66
Time Step 67
Time Step 68
Time Step 69
Time Step 70
Time Step 71
Time Step 72
Time Step 73
Time Step 

## Policy Iteration

In [20]:
import numpy as np


def compute_value_function(policy, env, num_iterations=1000, threshold=1e-10, gamma=1.0):
    # Initialize value table
    value_table = np.zeros(env.observation_space.n)

    for i in range(num_iterations):
        updated_value_table = np.copy(value_table)

        for s in range(env.observation_space.n):
            a = policy[s]
            value_table[s] = sum([
                prob * (r + gamma * updated_value_table[s_])
                for prob, s_, r, _ in env.unwrapped.P[s][a]
            ])

        if np.sum(np.fabs(updated_value_table - value_table)) <= threshold:
            break

    return value_table


def extract_policy(value_table, env, gamma=1.0):
    policy = np.zeros(env.observation_space.n)

    for s in range(env.observation_space.n):
        Q_values = [
            sum([prob * (r + gamma * value_table[s_])
                 for prob, s_, r, _ in env.unwrapped.P[s][a]])
            for a in range(env.action_space.n)
        ]
        policy[s] = np.argmax(np.array(Q_values))

    return policy


def policy_iteration(env, num_iterations=1000, threshold=1e-10, gamma=1.0):
    # Start with an arbitrary policy (all zeros = always take action 0)
    policy = np.zeros(env.observation_space.n)

    for i in range(num_iterations):
        # Step 1: Policy evaluation - compute value function for the current policy
        value_function = compute_value_function(policy, env, num_iterations, threshold, gamma)

        # Step 2: Policy improvement - extract a new, greedy policy from that value function
        new_policy = extract_policy(value_function, env, gamma)

        # Step 3: Check for convergence - has the policy stopped changing?
        if np.array_equal(new_policy, policy):
            print(f'Policy converged at iteration {i + 1}')
            break

        policy = new_policy

    return policy

In [23]:
import gymnasium as gym
import time

env = gym.make("FrozenLake-v1", render_mode="human")

policy = policy_iteration(env, num_iterations=1000, threshold=1e-10, gamma=1.0)
state, info = env.reset()
env.render()

num_timesteps = 100  # safety cap in case the agent never reaches a terminal state

for t in range(num_timesteps):
    action = int(policy[state])
    state, reward, done, truncated, info = env.step(action)
    print(f'Time Step {t + 1}')
    env.render()

    if done or truncated:
        print(f'Reached Terminal State {state} at time step {t + 1}')
        time.sleep(5)  
        break

env.close()

Policy converged at iteration 7
Time Step 1
Time Step 2
Time Step 3
Time Step 4
Time Step 5
Time Step 6
Time Step 7
Time Step 8
Time Step 9
Time Step 10
Time Step 11
Time Step 12
Time Step 13
Time Step 14
Time Step 15
Time Step 16
Time Step 17
Time Step 18
Time Step 19
Time Step 20
Time Step 21
Time Step 22
Time Step 23
Time Step 24
Time Step 25
Time Step 26
Time Step 27
Time Step 28
Time Step 29
Time Step 30
Time Step 31
Time Step 32
Time Step 33
Time Step 34
Time Step 35
Time Step 36
Time Step 37
Time Step 38
Time Step 39
Time Step 40
Time Step 41
Time Step 42
Time Step 43
Time Step 44
Time Step 45
Time Step 46
Time Step 47
Time Step 48
Time Step 49
Time Step 50
Time Step 51
Time Step 52
Time Step 53
Time Step 54
Time Step 55
Time Step 56
Time Step 57
Time Step 58
Time Step 59
Time Step 60
Time Step 61
Time Step 62
Time Step 63
Time Step 64
Time Step 65
Time Step 66
Time Step 67
Time Step 68
Time Step 69
Time Step 70
Time Step 71
Time Step 72
Time Step 73
Time Step 74
Time Step 75
Re