In [1]:
import torch

In [4]:
x = torch.randn(2, 3)
x

tensor([[-0.5691,  0.2928,  0.5255],
        [ 2.7278,  0.2311,  0.5592]])

In [5]:
x.sum()

tensor(3.7673)

In [9]:
x.sum(dim=1), x.sum(dim=1).shape

(tensor([0.2492, 3.5181]), torch.Size([2]))

In [10]:
x.sum(dim=1, keepdim=True), x.sum(dim=1, keepdim=True).shape

(tensor([[0.2492],
         [3.5181]]),
 torch.Size([2, 1]))

In [12]:
x = torch.randn(3, 2, 2)
x

tensor([[[-1.0441,  1.2539],
         [ 0.4703,  0.4898]],

        [[-1.8172, -0.2414],
         [ 1.3862, -1.7871]],

        [[ 1.2726,  0.6904],
         [ 1.9479,  2.5589]]])

In [13]:
x.sum(dim=0)

tensor([[-1.5888,  1.7028],
        [ 3.8044,  1.2615]])

In [14]:
x[0,:, :] + x[1, :, :] + x[2, :, :]

tensor([[-1.5888,  1.7028],
        [ 3.8044,  1.2615]])

In [15]:
x.sum(dim=0, keepdim=True)

tensor([[[-1.5888,  1.7028],
         [ 3.8044,  1.2615]]])

In [18]:
x

tensor([[[-1.0441,  1.2539],
         [ 0.4703,  0.4898]],

        [[-1.8172, -0.2414],
         [ 1.3862, -1.7871]],

        [[ 1.2726,  0.6904],
         [ 1.9479,  2.5589]]])

In [17]:
x.sum(dim=1), x.sum(dim=1).shape

(tensor([[-0.5739,  1.7436],
         [-0.4310, -2.0286],
         [ 3.2205,  3.2493]]),
 torch.Size([3, 2]))

In [19]:
x.sum(dim=1, keepdim=True), x.sum(dim=1, keepdim=True).shape

(tensor([[[-0.5739,  1.7436]],
 
         [[-0.4310, -2.0286]],
 
         [[ 3.2205,  3.2493]]]),
 torch.Size([3, 1, 2]))

In [21]:
x

tensor([[[-1.0441,  1.2539],
         [ 0.4703,  0.4898]],

        [[-1.8172, -0.2414],
         [ 1.3862, -1.7871]],

        [[ 1.2726,  0.6904],
         [ 1.9479,  2.5589]]])

In [20]:
x.sum(dim=2), x.sum(dim=2).shape

(tensor([[ 0.2098,  0.9600],
         [-2.0587, -0.4009],
         [ 1.9630,  4.5068]]),
 torch.Size([3, 2]))

In [22]:
x.sum(dim=2, keepdim=True), x.sum(dim=2, keepdim=True).shape

(tensor([[[ 0.2098],
          [ 0.9600]],
 
         [[-2.0587],
          [-0.4009]],
 
         [[ 1.9630],
          [ 4.5068]]]),
 torch.Size([3, 2, 1]))

In [23]:
y = torch.arange(3)
y

tensor([0, 1, 2])

In [24]:
y.shape

torch.Size([3])

In [28]:
z = y.unsqueeze(0)
z

tensor([[0, 1, 2]])

In [29]:
z.shape

torch.Size([1, 3])

In [30]:
m = torch.randn(3, 2, 2)
m

tensor([[[-0.3862,  0.5885],
         [ 0.3609,  0.6713]],

        [[ 0.0372, -0.4338],
         [-1.1047,  0.0152]],

        [[-0.0368, -1.2590],
         [-0.5706, -0.5116]]])

In [ ]:
n = m.view(3, -1) 
n

tensor([[-0.3862,  0.5885,  0.3609,  0.6713],
        [ 0.0372, -0.4338, -1.1047,  0.0152],
        [-0.0368, -1.2590, -0.5706, -0.5116]])

In [35]:
a = torch.randn(4, 10)
b = torch.randn(4, 10)

c = torch.cat([a, b], dim=0)
c.shape

torch.Size([8, 10])

In [36]:
a = torch.randn(4, 10)
b = torch.randn(4, 10)

c = torch.cat([a, b], dim=1)
c.shape

torch.Size([4, 20])

In [37]:
a = torch.randn(4, 10)
b = torch.randn(4, 10)

c = torch.stack([a, b], dim=0)
c.shape

torch.Size([2, 4, 10])

In [38]:
a = torch.randn(4, 10)
b = torch.randn(4, 10)

c = torch.stack([a, b], dim=1)
c.shape

torch.Size([4, 2, 10])

In [39]:
a,b

(tensor([[-0.8274, -0.1893, -0.3275, -0.7517,  0.3984, -0.6026, -0.1796, -0.8182,
          -0.3723,  1.0328],
         [-0.0935,  0.6367,  1.1210,  0.9964, -0.3586, -0.9498,  1.0418, -0.0889,
           0.1371,  1.4661],
         [-1.0193, -0.1382, -0.3713, -1.7017,  0.6843, -0.3856, -0.0903, -0.1282,
          -2.8101,  0.4503],
         [ 0.1059,  0.3693,  0.8761, -0.5974,  1.4251, -1.5907, -0.0525, -1.1842,
           1.8456, -1.5634]]),
 tensor([[ 0.1030, -0.7574,  0.8184, -1.1741,  0.7213, -0.2275,  0.9414, -0.3049,
           0.0962, -0.7131],
         [-2.2794, -0.7436, -0.3632,  0.4272, -1.7504,  0.4800,  0.0705, -0.7544,
          -0.6185,  0.2119],
         [ 0.2539, -0.0831,  0.8404, -0.1450, -1.9686,  0.5279, -0.5208,  0.3936,
          -0.7447, -0.8040],
         [ 0.7745,  1.8773,  1.2746,  0.5986, -0.8023, -0.1311,  0.2483,  0.8890,
           0.0197,  1.3104]]))

In [40]:
c

tensor([[[-0.8274, -0.1893, -0.3275, -0.7517,  0.3984, -0.6026, -0.1796,
          -0.8182, -0.3723,  1.0328],
         [ 0.1030, -0.7574,  0.8184, -1.1741,  0.7213, -0.2275,  0.9414,
          -0.3049,  0.0962, -0.7131]],

        [[-0.0935,  0.6367,  1.1210,  0.9964, -0.3586, -0.9498,  1.0418,
          -0.0889,  0.1371,  1.4661],
         [-2.2794, -0.7436, -0.3632,  0.4272, -1.7504,  0.4800,  0.0705,
          -0.7544, -0.6185,  0.2119]],

        [[-1.0193, -0.1382, -0.3713, -1.7017,  0.6843, -0.3856, -0.0903,
          -0.1282, -2.8101,  0.4503],
         [ 0.2539, -0.0831,  0.8404, -0.1450, -1.9686,  0.5279, -0.5208,
           0.3936, -0.7447, -0.8040]],

        [[ 0.1059,  0.3693,  0.8761, -0.5974,  1.4251, -1.5907, -0.0525,
          -1.1842,  1.8456, -1.5634],
         [ 0.7745,  1.8773,  1.2746,  0.5986, -0.8023, -0.1311,  0.2483,
           0.8890,  0.0197,  1.3104]]])

In [41]:
a = torch.randn(4, 10)
b = torch.randn(4, 10)

c = torch.stack([a, b], dim=2)
c.shape

torch.Size([4, 10, 2])

In [43]:
a, b

(tensor([[-0.5714,  0.3521, -2.0578, -0.3052,  2.5848, -0.7222, -0.4290,  1.5965,
           0.4136,  1.1352],
         [-0.0135, -0.4912,  0.2208, -0.2925,  0.2986,  1.0503, -1.2530,  0.0830,
          -0.1195, -0.0225],
         [ 1.4853, -1.3534, -0.1432,  0.5274,  0.4603,  1.9141, -0.1831, -0.8756,
          -0.4875,  0.9527],
         [ 1.3287, -0.1396,  0.4536,  0.1080,  0.3246, -0.7146,  0.9042, -1.2556,
           1.1560, -1.9941]]),
 tensor([[-0.6470, -2.5435, -1.6110, -0.9216,  0.0678,  0.3209,  1.7951,  0.8813,
           0.4180,  0.9420],
         [ 0.1238,  0.1157,  0.6477, -0.8061, -0.1623, -0.5084, -0.3999,  0.2821,
           1.5024, -0.2039],
         [ 1.1795, -1.2957, -0.1791,  0.7118,  1.1004, -0.6905,  1.0271,  0.6242,
           2.4379,  0.9589],
         [-0.7696,  0.5228, -1.2674, -0.7219,  1.4355,  0.0825,  1.0874, -0.7268,
          -0.4539, -1.3692]]))

In [42]:
c

tensor([[[-0.5714, -0.6470],
         [ 0.3521, -2.5435],
         [-2.0578, -1.6110],
         [-0.3052, -0.9216],
         [ 2.5848,  0.0678],
         [-0.7222,  0.3209],
         [-0.4290,  1.7951],
         [ 1.5965,  0.8813],
         [ 0.4136,  0.4180],
         [ 1.1352,  0.9420]],

        [[-0.0135,  0.1238],
         [-0.4912,  0.1157],
         [ 0.2208,  0.6477],
         [-0.2925, -0.8061],
         [ 0.2986, -0.1623],
         [ 1.0503, -0.5084],
         [-1.2530, -0.3999],
         [ 0.0830,  0.2821],
         [-0.1195,  1.5024],
         [-0.0225, -0.2039]],

        [[ 1.4853,  1.1795],
         [-1.3534, -1.2957],
         [-0.1432, -0.1791],
         [ 0.5274,  0.7118],
         [ 0.4603,  1.1004],
         [ 1.9141, -0.6905],
         [-0.1831,  1.0271],
         [-0.8756,  0.6242],
         [-0.4875,  2.4379],
         [ 0.9527,  0.9589]],

        [[ 1.3287, -0.7696],
         [-0.1396,  0.5228],
         [ 0.4536, -1.2674],
         [ 0.1080, -0.7219],
        